### PR TITLE
Invoke with current mouse position

### PR DESCRIPTION
**Pull request by kecleon**
sets the client's lastPressedX/Y so that the click x is on your actual mouse pos

### CODE REVIEW

**Comment by CommaDotComma** [comment]
This change isn't really necessary, the points should be tied to MouseBehavior enum, and there's an option to set it to current mouse position (MOUSE_POS).

**Comment by kecleon** [comment]
Ok, I see. 

> MouseBehavior enum

Well this isn't visible when you are on invoke or packets interaction type, maybe that should be changed instead?

**Comment by CommaDotComma** [comment]
I think it should be changed as well.

**Comment by kecleon** [comment]
> I think it should be changed as well.

Ok I'll make a new pr for that.

**Pull request closed without merging**
